management: # spring-boot-starter-acturator
  port: 8088 #自定义管理端口 管理端口就不用加context-path定义的前缀了  如：http://localhost:8088/health和http://localhost:8088/hystrix.stream
spring:
  application:
    name: consumer-movie-ribbon-with-hystrix3
server:
  port: 7901
  context-path: /ribbon
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:passwd@localhost:8000/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      management.port: 8088
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
