spring:
  application:
    name: EUREKA-HA
---
server:
  port: 8001
spring:
  profiles: eureka1  #jar包启动 后加--spring.profiles.active=eureka1
eureka:
  instance:
    hostname: eureka1  
  client:
    serviceUrl:
      defaultZone: http://eureka2:8002/eureka/,http://eureka3:8003/eureka/
---
server:
  port: 8002
spring:
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka3:8003/eureka/
---
server:
  port: 8003
spring:
  profiles: eureka3
eureka:
  instance:
    hostname: eureka3
  client:
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/