spring:
  application:
    name: consumer-movie-feign
server:
  port: 7901
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:passwd@localhost:8000/eureka
  instance:
    prefer-ip-address: true