server:
  port: 8020
spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:passwd@localhost:8000/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX3
  appConfig: consumer-movie-ribbon-with-hystrix3
  
logging: 
  level:
    root: INFO
    com.netflix.turbine.monitor: DEBUG