spring:
  application:
    name: gateway-zuul
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://root:passwd@localhost:8000/eureka
  instance:
    prefer-ip-address: true
