spring:
  application:
    name: gateway-zuul
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://root:passwd@localhost:8000/eureka
  instance:
    prefer-ip-address: true
    
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

